#!/usr/bin/perl

use strict;
use Dumpvalue;

sub oct_hex {
    my $org_num = shift;
    my $hope_num = shift;
    my $result_array = shift;
    my $r_max = shift;
    my $result_str_org = shift || undef;
    my $r_num = shift || 0;
    my $result_num_hex;
    my $result_num_oct;

    $r_num += 1;
    # hex
    my $result_str_hex = 'hex '.$result_str_org;
    eval{
        $result_num_hex = hex($org_num);
    };

    if($result_num_hex eq $hope_num) {
        push(@$result_array,$result_str_hex);
        return $result_array;
    }

    # oct
    my $result_str_oct = 'oct '.$result_str_org;
    eval{
        $result_num_oct = oct($org_num);
    };

    if($result_num_oct eq $hope_num) {
        push(@$result_array,$result_str_oct);
        return $result_array;
    }

    if ($r_num > $r_max) {
        return $result_array;
    }
    $result_array = oct_hex($result_num_hex,$hope_num,$result_array,$r_max,$result_str_hex,$r_num);
    $result_array = oct_hex($result_num_oct,$hope_num,$result_array,$r_max,$result_str_oct,$r_num);

    return $result_array;
}

sub get_hex_oct {
    my $character = shift;

    my $r_max = 5;
    my @base_num = (10,11,12,13);

    my @result_array;
    my %result;
    while(!@result_array) {
        foreach (@base_num) {
            print 'base_num:'.$_,' char:'.$character."\n";
            $result{$_} = oct_hex($_,$character,\@result_array,$r_max);
        }
        $r_max += 5;
    }
    my $d = Dumpvalue->new();
    #$d->dumpValues(%result);
    #$d->dumpValues($result{11});
    print $result{11}->[0],"\n";
    #$d->dumpValues(@result_array);
}

sub wwencode {
    my $text = shift;
    my $r = "";
    for (my $i = 0; $i < length($text); $i++) {
        my $code = get_hex_oct(ord(substr($text, $i, 1)));
        if ($code ne '') {
            $r .= 'and print chr ' . $code;
        }
    }
    return $r;
}

print "#!/usr/bin/werl\n";
#print "print chr oct length q wWWWWW WWWWWWw ";
print "WWwwWW WWww wWwww wwwWWWw W wWWWWW WWWWWWw ";
while (my $line = <>) {
    print wwencode($line);
}
print "\n";

1;

